// <auto-generated />
using ExcelFileProcessing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExcelFileProcessing.Migrations
{
    [DbContext(typeof(ExcelFileProcessingContext))]
    [Migration("20210108130741_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ExcelFileProcessing.Models.QAShipment", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BufferLotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterLotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalSpikedConcentration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matrix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatrixClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepAnalyst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QAClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("QAShipment");
                });
#pragma warning restore 612, 618
        }
    }
}
